<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Biodiversity, Endangerement and Conversation in Data from National Parks Service</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="biodiversity_files/libs/clipboard/clipboard.min.js"></script>
<script src="biodiversity_files/libs/quarto-html/quarto.js"></script>
<script src="biodiversity_files/libs/quarto-html/popper.min.js"></script>
<script src="biodiversity_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="biodiversity_files/libs/quarto-html/anchor.min.js"></script>
<link href="biodiversity_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="biodiversity_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="biodiversity_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="biodiversity_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="biodiversity_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Biodiversity, Endangerement and Conversation in Data from National Parks Service</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This project explores biodiversity data from the National Parks Service about endangered species in various parks. In particular, the project devles into the conservation statuses of endangered species to see if there are any patterns regarding the type of species the become endangered. The goal of this project will be to perform an Exploratory Data Analysis and explain findings from the analysis in a meaningful way.</p>
<p><strong>Sources:</strong> Both <code>Observations.csv</code> and <code>Species_info.csv</code> was provided by <a href="https://www.codecademy.com">Codecademy.com</a>.</p>
<section id="project-goals" class="level3">
<h3 class="anchored" data-anchor-id="project-goals">Project Goals</h3>
<p>The project will analyze data from the National Parks Service, with the goal of understanding characteristics about species and their conservations status, and the relationship between those species and the national parks they inhabit.</p>
<p>Some of the questions to be tackled include:</p>
<ul>
<li>What is the distribution of conservation status for animals?</li>
<li>Are certain types of species more likely to be endangered?</li>
<li>Are the differences between species and their conservation status significant?</li>
<li>Which species were spotted the most at each park?</li>
</ul>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>The project makes use of two datasets. The first dataset contains data about different species and their conservation statuses. The second dataset holds recorded sightings of different species at several national parks for 7 days.</p>
</section>
<section id="analysis" class="level3">
<h3 class="anchored" data-anchor-id="analysis">Analysis</h3>
<p>The analysis consists of the use of descriptive statistics and data visualization techniques to understand the data. Some of the key metrics that will be computed include:</p>
<ol type="1">
<li>Distribution of conservation statuses</li>
<li>Amount of intervention per species category</li>
<li>P-values for animal pairs and conservation statuses</li>
<li>Number of observations per park and species category</li>
</ol>
</section>
<section id="evaluation" class="level3">
<h3 class="anchored" data-anchor-id="evaluation">Evaluation</h3>
<p>Lastly, the project will revisit its initial goals and summarize the findings using the research questions. This section will also suggest additional questions which may expand on limitations in the current analysis and further guide future analyses on the subject.</p>
</section>
</section>
<section id="importing-modules-and-data-from-files" class="level2">
<h2 class="anchored" data-anchor-id="importing-modules-and-data-from-files">Importing Modules and Data from Files</h2>
<p>First, we will import the preliminary modules for this project, along with the data from the two separate files provided for this analysis.</p>
<div id="4379ec22" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>observations <span class="op">=</span> pd.read_csv(<span class="st">'observations.csv'</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>species <span class="op">=</span> pd.read_csv(<span class="st">'species_info.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="preview-the-data" class="level2">
<h2 class="anchored" data-anchor-id="preview-the-data">Preview the Data</h2>
<p>To prepare the data for analysis, we’ll scope both datasets using the <code>.sample()</code> and <code>.info()</code> functions.</p>
<section id="species.csv" class="level3">
<h3 class="anchored" data-anchor-id="species.csv"><code>species.csv</code></h3>
<div id="98d587d6" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>species.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 5824 entries, 0 to 5823
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   category             5824 non-null   object
 1   scientific_name      5824 non-null   object
 2   common_names         5824 non-null   object
 3   conservation_status  191 non-null    object
dtypes: object(4)
memory usage: 182.1+ KB</code></pre>
</div>
</div>
<p>The <code>species</code> dataset shows 5824 entries with four variables:</p>
<ul>
<li><strong>category</strong>: taxonomy for each species.</li>
<li><strong>scientific_name</strong>: scientific name of each species.</li>
<li><strong>common_names</strong>: common names of each species.</li>
<li><strong>conservation_status</strong>: species’ conservation status.</li>
</ul>
<p>According to the <code>.info()</code>, the last column shows a discrepant amount of entries (191) compared to the total number of entries in the dataset, demonstrating there is missing data.</p>
<p>Regarding data types, columns may remain as objects, since they do not contain neither numerical nor ordinal variables. An argument could be made for <code>conservation_status</code> given its ordinal nature. However, since not all values of conservation_statuses are present, and since the position of <code>in recovery</code> as an ordinal variable is ambiguous, the column may be left alone as an object. Nevertheless, below we preview a few rows from the dataset.</p>
<div id="35d79dcd" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>display(species.sample(<span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">category</th>
<th data-quarto-table-cell-role="th">scientific_name</th>
<th data-quarto-table-cell-role="th">common_names</th>
<th data-quarto-table-cell-role="th">conservation_status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1054</td>
<td>Vascular Plant</td>
<td>Microthlaspi perfoliatum</td>
<td>Claspleaf Pennycress</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2815</td>
<td>Nonvascular Plant</td>
<td>Brachythecium plumosum</td>
<td>Brachythecium Moss</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1493</td>
<td>Vascular Plant</td>
<td>Sabatia campanulata</td>
<td>Campanulate Sabatia, Slender Marsh Pink</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1289</td>
<td>Vascular Plant</td>
<td>Phlox subulata</td>
<td>Moss Phlox</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2569</td>
<td>Vascular Plant</td>
<td>Laportea canadensis</td>
<td>Wood Nettle, Wood-Nettle</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</section>
<section id="observations.csv" class="level3">
<h3 class="anchored" data-anchor-id="observations.csv"><code>observations.csv</code></h3>
<div id="813ea671" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>display(observations.info(), <span class="st">'</span><span class="ch">\n</span><span class="st">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 23296 entries, 0 to 23295
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   scientific_name  23296 non-null  object
 1   park_name        23296 non-null  object
 2   observations     23296 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 546.1+ KB</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>None</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>'\n'</code></pre>
</div>
</div>
<p>According to the information displayed above, the <code>observations</code> dataset contains there are three columns:</p>
<ul>
<li><strong>scientific_name</strong>: scientific name of each species.</li>
<li><strong>park_name</strong>: name of the national park species are located in.</li>
<li><strong>observations</strong>: number of observations in the past 7 days.</li>
</ul>
<p>The columns don’t show any missing data, and the data types seem to be appropriate for the analysis. Below we preview a sample of the rows.</p>
<div id="63abf2ff" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>observations.sample(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">scientific_name</th>
<th data-quarto-table-cell-role="th">park_name</th>
<th data-quarto-table-cell-role="th">observations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">18667</td>
<td>Quercus muehlenbergii</td>
<td>Yosemite National Park</td>
<td>171</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">22006</td>
<td>Trifolium breweri</td>
<td>Great Smoky Mountains National Park</td>
<td>68</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3559</td>
<td>Philonotis fontana var. pumila</td>
<td>Great Smoky Mountains National Park</td>
<td>53</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">17945</td>
<td>Nyctanassa violacea</td>
<td>Yosemite National Park</td>
<td>148</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14078</td>
<td>Cryptantha glomeriflora</td>
<td>Bryce National Park</td>
<td>77</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</section>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<section id="species.csv-1" class="level3">
<h3 class="anchored" data-anchor-id="species.csv-1"><code>species.csv</code></h3>
<p>We will start by exploring the <code>species</code> dataset more in detail. To explore the characteristics of each column, we’ve created a function that loops over the columns and prints out the unique value count, the null value count, and a preview of the top most frequent values along with their counts.</p>
<div id="ca145561" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> column_eda(dataset):</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    cols <span class="op">=</span> <span class="bu">list</span>(dataset.columns)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col <span class="kw">in</span> cols:</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'---------------</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">---------------'</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'Unique values:'</span>, dataset[col].nunique(), </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>              <span class="ss">f'Non-null values: </span><span class="sc">{</span>dataset[col]<span class="sc">.</span>notnull()<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss">'</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>              <span class="ss">f'Missing values: </span><span class="sc">{</span>dataset[col]<span class="sc">.</span>isnull()<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ch">\n</span><span class="ss">'</span>, </span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>              sep<span class="op">=</span><span class="st">'</span><span class="ch">\n</span><span class="st">'</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(dataset[col].value_counts().reset_index().head(<span class="dv">4</span>))</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>column_eda(species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>---------------category---------------
Unique values:
7
Non-null values: 5824
Missing values: 0

            category  count
0     Vascular Plant   4470
1               Bird    521
2  Nonvascular Plant    333
3             Mammal    214
---------------scientific_name---------------
Unique values:
5541
Non-null values: 5824
Missing values: 0

        scientific_name  count
0     Castor canadensis      3
1           Canis lupus      3
2  Hypochaeris radicata      3
3         Columba livia      3
---------------common_names---------------
Unique values:
5504
Non-null values: 5824
Missing values: 0

         common_names  count
0  Brachythecium Moss      7
1       Dicranum Moss      7
2         Panic Grass      6
3          Bryum Moss      6
---------------conservation_status---------------
Unique values:
4
Non-null values: 191
Missing values: 5633

  conservation_status  count
0  Species of Concern    161
1          Endangered     16
2          Threatened     10
3         In Recovery      4</code></pre>
</div>
</div>
<p>The function shows there are 7 categories of species, 5541 species, 5504 common names and 4 conservation statuses. Some preliminary remarks can be made from a first glance:</p>
<ol type="1">
<li><code>conservation_status</code> displays a high number of <code>nan</code> values (5633), which, given the available categories, may well be treated as ‘species of no concern’ or with ‘no intervention’.</li>
</ol>
<p>To attend this, I’ll change the missing values in the <code>conservation_status</code> column to “No intervention”, giving this column a total of 5 statuses.</p>
<div id="36c91b81" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Old conservation status:</span><span class="ch">\n</span><span class="st">'</span>, <span class="bu">list</span>(species.conservation_status.unique()))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>species.conservation_status <span class="op">=</span> species.conservation_status.fillna(<span class="st">'No intervention'</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'New conservation status:</span><span class="ch">\n</span><span class="st">'</span>, <span class="bu">list</span>(species.conservation_status.unique()))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Old conservation status:
 [nan, 'Species of Concern', 'Endangered', 'Threatened', 'In Recovery']
New conservation status:
 ['No intervention', 'Species of Concern', 'Endangered', 'Threatened', 'In Recovery']</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>There is a discrepancy between the number of unique values of <code>scientific_name</code> and <code>common_names</code> despite all entries having non-null values. This points to the presence of duplicate common names for different species.</li>
</ol>
<p>To confirm this claim, I’ll scope both columns for duplicates.</p>
<div id="8f86549d" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>duplicates <span class="op">=</span> species.duplicated().<span class="bu">sum</span>()</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Overall duplicates (rows): </span><span class="sc">{</span>duplicates<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>repeated_scientific_names <span class="op">=</span> species.duplicated(subset<span class="op">=</span>[<span class="st">'scientific_name'</span>]).<span class="bu">sum</span>()</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Duplicated scientific names: </span><span class="sc">{</span>repeated_scientific_names<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>repeated_common_names <span class="op">=</span>species.duplicated(subset<span class="op">=</span>[<span class="st">'common_names'</span>]).<span class="bu">sum</span>() </span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Duplicated common names: </span><span class="sc">{</span>repeated_common_names<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Overall duplicates (rows): 0
Duplicated scientific names: 283
Duplicated common names: 320</code></pre>
</div>
</div>
<p>The presence of more duplicates for common names than scientific names confirms the existence of multiple species having the same common name. To demonstrate this, we will print the most frequent common name along with the corresponding scientific names attached to it.</p>
<div id="d8b7315a" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>display(species.common_names.value_counts().reset_index()[:<span class="dv">5</span>])</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>display(species.query(<span class="st">"common_names == 'Brachythecium Moss'"</span>)[[<span class="st">'common_names'</span>, <span class="st">'scientific_name'</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">common_names</th>
<th data-quarto-table-cell-role="th">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Brachythecium Moss</td>
<td>7</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Dicranum Moss</td>
<td>7</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Panic Grass</td>
<td>6</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Bryum Moss</td>
<td>6</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Sphagnum</td>
<td>6</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">common_names</th>
<th data-quarto-table-cell-role="th">scientific_name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">2812</td>
<td>Brachythecium Moss</td>
<td>Brachythecium digastrum</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2813</td>
<td>Brachythecium Moss</td>
<td>Brachythecium oedipodium</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2814</td>
<td>Brachythecium Moss</td>
<td>Brachythecium oxycladon</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2815</td>
<td>Brachythecium Moss</td>
<td>Brachythecium plumosum</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2816</td>
<td>Brachythecium Moss</td>
<td>Brachythecium rivulare</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2817</td>
<td>Brachythecium Moss</td>
<td>Brachythecium rutabulum</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2818</td>
<td>Brachythecium Moss</td>
<td>Brachythecium salebrosum</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>As seen above, the most frequent common name is <em>Brachythecium Moss</em>, with a total of 7 different species named as such. Organisms in this example all share the same genus (i.e.&nbsp;brachythecium, a genus of moss), but differ in species, thus the different scientific names.</p>
<p>Another open question is the fact that there are duplicates in <code>scientific_name</code>. Since the dataset contains observations about the different species, one would expect for there to be one observation per species. However, the duplicate scientific names indicate the presence of duplicate observations of the same species in the dataset.</p>
<p>Since there are no overall duplicates in the dataset (see above), these duplicate names must have some difference at the row level. To delve deeper into this, we’ll print out a sample of duplicates and inspect three random dumplicates species, to see what kind of differences are there within the rows themselves.</p>
<div id="7165af93" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>duplicated_species <span class="op">=</span> species[species[<span class="st">'scientific_name'</span>].duplicated(keep<span class="op">=</span><span class="va">False</span>)]</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>display(<span class="st">'-------Sample of duplicated scientific names-------'</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>display(duplicated_species.head())</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> display_duplicated_species(scientific_name):</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    duplicated_entries <span class="op">=</span> duplicated_species[duplicated_species[<span class="st">'scientific_name'</span>] <span class="op">==</span> scientific_name]</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    display(<span class="ss">f'-------Duplicated </span><span class="ch">\'</span><span class="sc">{</span>scientific_name<span class="sc">}</span><span class="ch">\'</span><span class="ss">-------'</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    display(duplicated_entries)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>scientific_names_to_check <span class="op">=</span> [<span class="st">'Cervus elaphus'</span>, <span class="st">'Canis lupus'</span>, <span class="st">'Odocoileus virginianus'</span>]</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> scientific_name <span class="kw">in</span> scientific_names_to_check:</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    display_duplicated_species(scientific_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>'-------Sample of duplicated scientific names-------'</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">category</th>
<th data-quarto-table-cell-role="th">scientific_name</th>
<th data-quarto-table-cell-role="th">common_names</th>
<th data-quarto-table-cell-role="th">conservation_status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Mammal</td>
<td>Cervus elaphus</td>
<td>Wapiti Or Elk</td>
<td>No intervention</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Mammal</td>
<td>Odocoileus virginianus</td>
<td>White-Tailed Deer</td>
<td>No intervention</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>Mammal</td>
<td>Sus scrofa</td>
<td>Feral Hog, Wild Pig</td>
<td>No intervention</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">8</td>
<td>Mammal</td>
<td>Canis lupus</td>
<td>Gray Wolf</td>
<td>Endangered</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>Mammal</td>
<td>Urocyon cinereoargenteus</td>
<td>Common Gray Fox, Gray Fox</td>
<td>No intervention</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell-output cell-output-display">
<pre><code>"-------Duplicated 'Cervus elaphus'-------"</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">category</th>
<th data-quarto-table-cell-role="th">scientific_name</th>
<th data-quarto-table-cell-role="th">common_names</th>
<th data-quarto-table-cell-role="th">conservation_status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Mammal</td>
<td>Cervus elaphus</td>
<td>Wapiti Or Elk</td>
<td>No intervention</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3017</td>
<td>Mammal</td>
<td>Cervus elaphus</td>
<td>Rocky Mountain Elk</td>
<td>No intervention</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell-output cell-output-display">
<pre><code>"-------Duplicated 'Canis lupus'-------"</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">category</th>
<th data-quarto-table-cell-role="th">scientific_name</th>
<th data-quarto-table-cell-role="th">common_names</th>
<th data-quarto-table-cell-role="th">conservation_status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>Mammal</td>
<td>Canis lupus</td>
<td>Gray Wolf</td>
<td>Endangered</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3020</td>
<td>Mammal</td>
<td>Canis lupus</td>
<td>Gray Wolf, Wolf</td>
<td>In Recovery</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4448</td>
<td>Mammal</td>
<td>Canis lupus</td>
<td>Gray Wolf, Wolf</td>
<td>Endangered</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell-output cell-output-display">
<pre><code>"-------Duplicated 'Odocoileus virginianus'-------"</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">category</th>
<th data-quarto-table-cell-role="th">scientific_name</th>
<th data-quarto-table-cell-role="th">common_names</th>
<th data-quarto-table-cell-role="th">conservation_status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>Mammal</td>
<td>Odocoileus virginianus</td>
<td>White-Tailed Deer</td>
<td>No intervention</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3019</td>
<td>Mammal</td>
<td>Odocoileus virginianus</td>
<td>White-Tailed Deer, White-Tailed Deer</td>
<td>No intervention</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>It seems that both the number of common names and the types of conservation statuses are different for duplicate observations. That is, the same species exhibits both different common names, as well as conservation statuses. To solve the question of duplicates, given the differences in conversation statuses do not affect our question on the likelihood of endangerment given a species’ protection status, I’ll retain the first instance of these duplicates.</p>
<div id="c3be4a14" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>species <span class="op">=</span> species.drop_duplicates(subset <span class="op">=</span> [<span class="st">'scientific_name'</span>], keep<span class="op">=</span> <span class="st">'first'</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>repeated_scientific_names <span class="op">=</span> species.scientific_name[species.scientific_name.duplicated()]</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Duplicated scientific names: </span><span class="sc">{</span><span class="bu">len</span>(repeated_scientific_names)<span class="sc">}</span><span class="ch">\n</span><span class="ss">'</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'-------Previously duplicated examples (now clean)-------'</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>scientific_names_to_check <span class="op">=</span> [<span class="st">'Cervus elaphus'</span>, <span class="st">'Canis lupus'</span>, <span class="st">'Odocoileus virginianus'</span>]</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>display(species[species[<span class="st">'scientific_name'</span>].isin(scientific_names_to_check)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Duplicated scientific names: 0

-------Previously duplicated examples (now clean)-------</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">category</th>
<th data-quarto-table-cell-role="th">scientific_name</th>
<th data-quarto-table-cell-role="th">common_names</th>
<th data-quarto-table-cell-role="th">conservation_status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Mammal</td>
<td>Cervus elaphus</td>
<td>Wapiti Or Elk</td>
<td>No intervention</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Mammal</td>
<td>Odocoileus virginianus</td>
<td>White-Tailed Deer</td>
<td>No intervention</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>Mammal</td>
<td>Canis lupus</td>
<td>Gray Wolf</td>
<td>Endangered</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</section>
<section id="observations.csv-1" class="level3">
<h3 class="anchored" data-anchor-id="observations.csv-1"><code>observations.csv</code></h3>
<p>I’ll perform the same analysis as above with the second dataset. I’ll scope the columns for unique values, the amount of nun-null values, and the top most frequent values along with their counts.</p>
<div id="301e9192" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>column_eda(observations)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>---------------scientific_name---------------
Unique values:
5541
Non-null values: 23296
Missing values: 0

        scientific_name  count
0      Myotis lucifugus     12
1         Puma concolor     12
2  Hypochaeris radicata     12
3        Holcus lanatus     12
---------------park_name---------------
Unique values:
4
Non-null values: 23296
Missing values: 0

                             park_name  count
0  Great Smoky Mountains National Park   5824
1               Yosemite National Park   5824
2                  Bryce National Park   5824
3            Yellowstone National Park   5824
---------------observations---------------
Unique values:
304
Non-null values: 23296
Missing values: 0

   observations  count
0            84    220
1            85    210
2            91    206
3            92    203</code></pre>
</div>
</div>
<p>The EDA for this dataset reveals there 23296 observations of 5541 unique species documented in 4 parks. The EDA for the <code>observations</code> column doesn’t reveal much useful information, given this is a numerical variable.</p>
<p>However, this variable may proove usefull in answering some of the questions introduced above. To better explore this column given its data type, I’ll provide here some descriptive statistics on it.</p>
<div id="b5e07aa3" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(observations.observations.describe())</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>sns.histplot(x <span class="op">=</span> <span class="st">'observations'</span>, data <span class="op">=</span> observations, kde<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Total number of observations:'</span>, observations.observations.<span class="bu">sum</span>(), <span class="st">'in the past 7 days.'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>count    23296.000000
mean       142.287904
std         69.890532
min          9.000000
25%         86.000000
50%        124.000000
75%        195.000000
max        321.000000
Name: observations, dtype: float64
Total number of observations: 3314739 in the past 7 days.</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="biodiversity_files/figure-html/cell-14-output-2.png" width="601" height="429" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">Summary</h3>
<p>To summarize the findings of this EDA, I outline below the chief characteristics of both datasets.</p>
<section id="species" class="level4">
<h4 class="anchored" data-anchor-id="species"><code>species</code></h4>
<ul>
<li>Has 4 variables: category (the species taxonomy), scientific_name, common_names and conservation_status.</li>
<li>All variables are either categorical or nominal.</li>
<li>The data shows observations for 5541 unique species among 7 types, having 5504 common names and displaying 5 conservation statuses.</li>
</ul>
</section>
<section id="observations" class="level4">
<h4 class="anchored" data-anchor-id="observations"><code>observations</code></h4>
<ul>
<li>Has 3 variables: scientific_name, park_name and number of observations in the past 7 days.</li>
<li>The variables are nominal, categorical and numerical respectively.</li>
<li>The data shows 23296 entries of 5541 unique species documented in 4 parks in a total of 3314739 observations in the past 7 days.</li>
</ul>
</section>
</section>
</section>
<section id="analysis-1" class="level2">
<h2 class="anchored" data-anchor-id="analysis-1">Analysis</h2>
<p>For this analysis, I’ll attempt to answer the questions stated above by beginning with the <code>species</code> dataset.</p>
<section id="q-what-is-the-distribution-of-conservation-status-for-animals" class="level3">
<h3 class="anchored" data-anchor-id="q-what-is-the-distribution-of-conservation-status-for-animals">Q: What is the distribution of conservation status for animals?</h3>
<p>First, I’ll explore the distribution of animal categories among conservation statuses by grouping the <code>species</code> dataset by both columns and calculating the absolute and relative frequencies by conservation status. Then, I’ll plot them below.</p>
<p>The most endangered animals in the dataset were mammals (6) and birds (4), while the only animal in recovery are birds (3), which could point to the fact that birds are recovering better than other animals.</p>
<p>The distribution of species among categories and conservation statuses is depicted in the following plot.</p>
<div id="f42cb06a" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>num_conservation <span class="op">=</span> <span class="bu">len</span>(species[species.conservation_status <span class="op">!=</span> <span class="st">'No intervention'</span>])</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>num_not_conservation <span class="op">=</span> <span class="bu">len</span>(species[species.conservation_status <span class="op">==</span> <span class="st">'No intervention'</span>])</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Total species under protection: </span><span class="sc">{</span>num_conservation<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Total species not under protection: </span><span class="sc">{</span>num_not_conservation<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>category_conservation <span class="op">=</span> species[species.conservation_status <span class="op">!=</span> <span class="st">'No intervention'</span>]<span class="op">\</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>                        .groupby([<span class="st">'conservation_status'</span>, <span class="st">'category'</span>])[<span class="st">'scientific_name'</span>]<span class="op">\</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>                        .count()<span class="op">\</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>                        .unstack()<span class="op">\</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>                        .replace(<span class="st">'nan'</span>, np.nan).fillna(<span class="dv">0</span>)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>display(<span class="st">"Absolute frequencies"</span>, category_conservation)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> category_conservation.plot(kind<span class="op">=</span><span class="st">'bar'</span>, figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">6</span>), stacked <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Conservation Status'</span>)</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Number of Species'</span>)</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Animal Distribution among Conservation Statuses"</span>)</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>plt.clf()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Total species under protection: 178
Total species not under protection: 5363</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>'Absolute frequencies'</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">category</th>
<th data-quarto-table-cell-role="th">Amphibian</th>
<th data-quarto-table-cell-role="th">Bird</th>
<th data-quarto-table-cell-role="th">Fish</th>
<th data-quarto-table-cell-role="th">Mammal</th>
<th data-quarto-table-cell-role="th">Nonvascular Plant</th>
<th data-quarto-table-cell-role="th">Reptile</th>
<th data-quarto-table-cell-role="th">Vascular Plant</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">conservation_status</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Endangered</td>
<td>1.0</td>
<td>4.0</td>
<td>3.0</td>
<td>6.0</td>
<td>0.0</td>
<td>0.0</td>
<td>1.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">In Recovery</td>
<td>0.0</td>
<td>3.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Species of Concern</td>
<td>4.0</td>
<td>68.0</td>
<td>4.0</td>
<td>22.0</td>
<td>5.0</td>
<td>5.0</td>
<td>43.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Threatened</td>
<td>2.0</td>
<td>0.0</td>
<td>3.0</td>
<td>2.0</td>
<td>0.0</td>
<td>0.0</td>
<td>2.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="biodiversity_files/figure-html/cell-15-output-4.png" width="816" height="638" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 672x480 with 0 Axes&gt;</code></pre>
</div>
</div>
<p>In addition to that, the relative frequencies per conservation status reveal more information about the distribution of animal categories per status. - Mammals, birds and fish make up more than 85% of all endangered species documented in the <code>species</code> dataset. - More than 70% of species of concern are made up of birds and vascular plants. - As observed before, birds make up 100% of the species in recovery according to the dataset.</p>
<p>These proportions can be clearly visualized in the plot below.</p>
<div id="3ebc057e" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>category_conservation_rel <span class="op">=</span> species[species.conservation_status <span class="op">!=</span> <span class="st">'No intervention'</span>]<span class="op">\</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                            .groupby([<span class="st">'category'</span>, <span class="st">'conservation_status'</span>])[<span class="st">'scientific_name'</span>]<span class="op">\</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>                            .count()<span class="op">\</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>                            .unstack()<span class="op">\</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>                            .replace(<span class="st">'nan'</span>, np.nan).fillna(<span class="dv">0</span>)<span class="op">\</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>                            .<span class="bu">apply</span>(<span class="kw">lambda</span> x:  (<span class="dv">100</span><span class="op">*</span>x <span class="op">/</span> x.<span class="bu">sum</span>()).<span class="bu">round</span>(<span class="dv">2</span>))<span class="op">\</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>                            .transpose()</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>display(<span class="st">"Relative frequencies by category"</span>, category_conservation_rel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>'Relative frequencies by category'</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">category</th>
<th data-quarto-table-cell-role="th">Amphibian</th>
<th data-quarto-table-cell-role="th">Bird</th>
<th data-quarto-table-cell-role="th">Fish</th>
<th data-quarto-table-cell-role="th">Mammal</th>
<th data-quarto-table-cell-role="th">Nonvascular Plant</th>
<th data-quarto-table-cell-role="th">Reptile</th>
<th data-quarto-table-cell-role="th">Vascular Plant</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">conservation_status</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Endangered</td>
<td>6.67</td>
<td>26.67</td>
<td>20.00</td>
<td>40.00</td>
<td>0.00</td>
<td>0.00</td>
<td>6.67</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">In Recovery</td>
<td>0.00</td>
<td>100.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Species of Concern</td>
<td>2.65</td>
<td>45.03</td>
<td>2.65</td>
<td>14.57</td>
<td>3.31</td>
<td>3.31</td>
<td>28.48</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Threatened</td>
<td>22.22</td>
<td>0.00</td>
<td>33.33</td>
<td>22.22</td>
<td>0.00</td>
<td>0.00</td>
<td>22.22</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<div id="c6a25455" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>axrel <span class="op">=</span> category_conservation_rel.plot(kind<span class="op">=</span><span class="st">'bar'</span>, figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">6</span>), stacked <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>axrel.set_xlabel(<span class="st">'Conservation Status'</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>axrel.set_ylabel(<span class="st">'Number of Species'</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>axrel.legend(bbox_to_anchor<span class="op">=</span>(<span class="dv">1</span>,<span class="dv">1</span>), loc <span class="op">=</span> <span class="st">'upper left'</span>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Proportions of Animals per Conservation Status"</span>)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>plt.clf()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="biodiversity_files/figure-html/cell-17-output-1.png" width="991" height="638" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 672x480 with 0 Axes&gt;</code></pre>
</div>
</div>
</section>
<section id="q-are-certain-types-of-species-more-likely-to-be-endangered" class="level3">
<h3 class="anchored" data-anchor-id="q-are-certain-types-of-species-more-likely-to-be-endangered">Q: Are certain types of species more likely to be endangered?</h3>
<p>The next question concerns the relation between species and their conservation status. To answer this question, I’ll group the conservation statuses into those reflecting some kind of intervention and those without. No intervention will become a marker for risk of endangerment.</p>
<p>After this I’ll group the species categories and calculate the amount protected and not protected.</p>
<div id="54372c26" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>species[<span class="st">'protected'</span>] <span class="op">=</span> species.conservation_status <span class="op">!=</span> <span class="st">'No intervention'</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>category_protections <span class="op">=</span> species.groupby([<span class="st">'category'</span>, <span class="st">'protected'</span>])<span class="op">\</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>                        .scientific_name.nunique()<span class="op">\</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>                        .reset_index()<span class="op">\</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>                        .pivot_table(columns <span class="op">=</span> <span class="st">'protected'</span>,</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>                                    index <span class="op">=</span> <span class="st">'category'</span>,</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>                                    values <span class="op">=</span> <span class="st">'scientific_name'</span>)<span class="op">\</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>                        .reset_index()</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>category_protections.columns <span class="op">=</span> [<span class="st">'category'</span>, <span class="st">'not_protected'</span>, <span class="st">'protected'</span>]</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>category_protections[<span class="st">'percentage_protected'</span>] <span class="op">=</span> (category_protections.protected <span class="op">/</span> <span class="op">\</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>                                                (category_protections.protected <span class="op">+</span> category_protections.not_protected) <span class="op">*</span> <span class="dv">100</span>)<span class="op">\</span></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>                                                .<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>display(category_protections)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">category</th>
<th data-quarto-table-cell-role="th">not_protected</th>
<th data-quarto-table-cell-role="th">protected</th>
<th data-quarto-table-cell-role="th">percentage_protected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Amphibian</td>
<td>72.0</td>
<td>7.0</td>
<td>8.86</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Bird</td>
<td>413.0</td>
<td>75.0</td>
<td>15.37</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Fish</td>
<td>115.0</td>
<td>10.0</td>
<td>8.00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Mammal</td>
<td>146.0</td>
<td>30.0</td>
<td>17.05</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Nonvascular Plant</td>
<td>328.0</td>
<td>5.0</td>
<td>1.50</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Reptile</td>
<td>73.0</td>
<td>5.0</td>
<td>6.41</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>Vascular Plant</td>
<td>4216.0</td>
<td>46.0</td>
<td>1.08</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>With this information, we can now visualize the percentages of protection for each species category. Based on this, mammals and birds display the highest proportion of protection with roughly 17% and 15% under protection, respectively. Thus, these species types are the most likely to be endangered among categories. The bar chart below visualizes the percentages per category.</p>
<div id="1c6fb72c" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">5</span>))</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>sns.barplot(data <span class="op">=</span> category_protections, y <span class="op">=</span> <span class="st">'percentage_protected'</span>, x <span class="op">=</span> <span class="st">'category'</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>plt.clf()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="biodiversity_files/figure-html/cell-19-output-1.png" width="808" height="429" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 672x480 with 0 Axes&gt;</code></pre>
</div>
</div>
</section>
<section id="q-are-the-differences-between-species-and-their-conservation-status-significant" class="level3">
<h3 class="anchored" data-anchor-id="q-are-the-differences-between-species-and-their-conservation-status-significant">Q: Are the differences between species and their conservation status significant?</h3>
<p>The question of statistical significance for categorical variables is answered in statistics by use of the chi-square test.</p>
<p>Since crosstabulating both variables would yield a complex result, it’s better to break down the question into pairs of species categories. Since based on the previous question mammals are the most protected category, I’ll compare the significance of other category differences with mammals.</p>
<p>I’ll start by permutating the pairs of categories with mammals. Then I’ll loop over this list to perform the chi-square tests for each pair and plot the p-values to find the statistically significant differences among category pairs.</p>
<div id="7f224630" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> chi2_contingency</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Permutations</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>categories <span class="op">=</span> <span class="bu">list</span>(species.category.unique())</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>combinations_mammal <span class="op">=</span> [[<span class="st">'Mammal'</span>, i] <span class="cf">for</span> i <span class="kw">in</span> categories][<span class="dv">1</span>:]</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>category_protections_part <span class="op">=</span> category_protections.iloc[:, <span class="dv">0</span>:<span class="dv">3</span>]</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>category_protections_part <span class="op">=</span> category_protections_part.set_index(<span class="st">'category'</span>)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Significant Differences Data</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>sign_data <span class="op">=</span> {<span class="st">'Animal Pair'</span>: [], <span class="st">'p-value'</span>: []}</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> pair <span class="kw">in</span> combinations_mammal:</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>    contingency_table <span class="op">=</span> pd.DataFrame({pair[<span class="dv">0</span>]: category_protections_part.loc[pair[<span class="dv">0</span>]],</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>                                    pair[<span class="dv">1</span>]: category_protections_part.loc[pair[<span class="dv">1</span>]]}) </span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>    chi2, pval, dof, expected <span class="op">=</span> chi2_contingency(contingency_table)</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>    sign_data[<span class="st">'Animal Pair'</span>].append(pair[<span class="dv">1</span>])</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>    sign_data[<span class="st">'p-value'</span>].append((pval<span class="op">*</span><span class="dv">100</span>).<span class="bu">round</span>(<span class="dv">2</span>))</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>sign_data <span class="op">=</span> pd.DataFrame(data <span class="op">=</span> sign_data).sort_values(<span class="st">'p-value'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>display(sign_data)</span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">5</span>))</span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span>sns.barplot(data <span class="op">=</span> sign_data, x <span class="op">=</span> <span class="st">'Animal Pair'</span>, y <span class="op">=</span> <span class="st">'p-value'</span>)</span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Statistical Significance of Protection Statuses per Animal</span><span class="ch">\n</span><span class="st">(difference with mammals)'</span>)</span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">5</span>, color<span class="op">=</span><span class="st">'red'</span>)</span>
<span id="cb39-25"><a href="#cb39-25" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">""</span>)</span>
<span id="cb39-26"><a href="#cb39-26" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'p-value in percent</span><span class="ch">\n</span><span class="st">(alpha = 5%)'</span>)</span>
<span id="cb39-27"><a href="#cb39-27" aria-hidden="true" tabindex="-1"></a><span class="co"># plt.xticks(rotation=45)</span></span>
<span id="cb39-28"><a href="#cb39-28" aria-hidden="true" tabindex="-1"></a>ax.bar_label(ax.containers[<span class="dv">0</span>])</span>
<span id="cb39-29"><a href="#cb39-29" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Animal Pair</th>
<th data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Bird</td>
<td>68.76</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>Amphibian</td>
<td>12.76</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>Reptile</td>
<td>3.84</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Fish</td>
<td>3.52</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Vascular Plant</td>
<td>0.00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Nonvascular Plant</td>
<td>0.00</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="biodiversity_files/figure-html/cell-20-output-2.png" width="823" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The above graph illustrates the p-values for the chi-square tests performed for each animal category against mammals. Given an alpha of 5%, the analysis shows that birds and amphibians display no statistically significant differences in their conservations statuses compared to mammals. However, all other categories such as reptiles, fishes and plants show statistically significant differences in their conservation statuses when comapred to mammals.</p>
</section>
<section id="q-which-species-were-spotted-the-most-at-each-park" class="level3">
<h3 class="anchored" data-anchor-id="q-which-species-were-spotted-the-most-at-each-park">Q: Which species were spotted the most at each park?</h3>
<p>This final section will concern the second dataset, <code>observations</code>, to quantify the amount of observations per species in each of the parks listed.</p>
<p>Since the dataset doesn’t include common names, I’ll use the <code>species</code> dataset to merge these names into the <code>observations</code> dataset. Then, I’ll group the data by park and by species/common names, and sum their observations to rank the most spoted species per park.</p>
<div id="c4717d7a" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>merged_df <span class="op">=</span> observations.merge(species[[<span class="st">'category'</span>, <span class="st">'scientific_name'</span>, <span class="st">'common_names'</span>]], how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>merged_df <span class="op">=</span> merged_df.drop_duplicates()</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>merged_df_grouped <span class="op">=</span> merged_df.groupby([<span class="st">'park_name'</span>, <span class="st">'scientific_name'</span>, <span class="st">'common_names'</span>, <span class="st">'category'</span>]).observations<span class="op">\</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>                        .<span class="bu">sum</span>().sort_values(ascending<span class="op">=</span><span class="va">False</span>)<span class="op">\</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>                        .reset_index()</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>display(merged_df_grouped.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">park_name</th>
<th data-quarto-table-cell-role="th">scientific_name</th>
<th data-quarto-table-cell-role="th">common_names</th>
<th data-quarto-table-cell-role="th">category</th>
<th data-quarto-table-cell-role="th">observations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Yellowstone National Park</td>
<td>Holcus lanatus</td>
<td>Common Velvet Grass, Velvetgrass</td>
<td>Vascular Plant</td>
<td>805</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Yellowstone National Park</td>
<td>Puma concolor</td>
<td>Panther (Mountain Lion)</td>
<td>Mammal</td>
<td>753</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Yellowstone National Park</td>
<td>Procyon lotor</td>
<td>Common Raccoon, Raccoon</td>
<td>Mammal</td>
<td>745</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Yellowstone National Park</td>
<td>Hypochaeris radicata</td>
<td>Cat's Ear, Spotted Cat's-Ear</td>
<td>Vascular Plant</td>
<td>726</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Yellowstone National Park</td>
<td>Columba livia</td>
<td>Rock Dove</td>
<td>Bird</td>
<td>722</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>The previous table shows the number of observations for each species, grouped by park. To answer the question above, I’ll create a table with the max value of observations per park, to show the species that was most spotted in each of the parks.</p>
<div id="63d31303" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>merged_df_grouped_max <span class="op">=</span> merged_df_grouped.loc[merged_df_grouped<span class="op">\</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>                                                    .groupby([<span class="st">'park_name'</span>])<span class="op">\</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>                                                    [<span class="st">'observations'</span>].idxmax()]<span class="op">\</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>                                                .sort_values(by <span class="op">=</span> <span class="st">'observations'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>display(merged_df_grouped_max)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">park_name</th>
<th data-quarto-table-cell-role="th">scientific_name</th>
<th data-quarto-table-cell-role="th">common_names</th>
<th data-quarto-table-cell-role="th">category</th>
<th data-quarto-table-cell-role="th">observations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Yellowstone National Park</td>
<td>Holcus lanatus</td>
<td>Common Velvet Grass, Velvetgrass</td>
<td>Vascular Plant</td>
<td>805</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">112</td>
<td>Yosemite National Park</td>
<td>Hypochaeris radicata</td>
<td>Cat's Ear, Spotted Cat's-Ear</td>
<td>Vascular Plant</td>
<td>505</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">298</td>
<td>Bryce National Park</td>
<td>Columba livia</td>
<td>Rock Dove</td>
<td>Bird</td>
<td>339</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2402</td>
<td>Great Smoky Mountains National Park</td>
<td>Streptopelia decaocto</td>
<td>Eurasian Collared-Dove</td>
<td>Bird</td>
<td>256</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</section>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<p>This project successfully answered the question stated at the beginning of this report, regarding the distribution of species and their conservation statuses among the four parks. To better explain the data, different visualizations were used to depict the conclusions to be drawn from the analysis.</p>
<p>Below is a summary of the answers to the questions posed at the start of the report:</p>
<ul>
<li>What is the distribution of conservation status for species?
<ul>
<li>5363 species are not protected under some conservation status. Of the remaining 178, most species are under the status of <em>species of concern</em>, especially birds and vascular plants.</li>
</ul></li>
<li>Are certain types of species more likely to be endangered?
<ul>
<li>Mammals and birds have the highest proportion of protection, revealing their higher risk of endangerement compared to the other categories.</li>
</ul></li>
<li>Are the differences between species and their conservation status significant?
<ul>
<li>In a comparisson with mammals, species such as amphibians, reptiles, fishes, and plants showed statistically significant differences in conservation proportion. Birds however did not exhibit a significant difference.</li>
</ul></li>
<li>Which animal is most prevalent and what is their distribution amongst parks?
<ul>
<li>The most common species recorded was the common velvet grass, a vascular plant, in Yellowstome National Park, while the Dove was the most commonly observed species both in Bryce and Great Smoky Mountains National Parks. In Yosemite the most observed species was the cat’s ear plant.</li>
</ul></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>